spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t6NT4miFifNCkgiAGuE
      secret-key: UGK3U8ObFidb3vLDoGiaXQW4OEBiJy
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-timecarol

  application:
    name: gulimall-third-party

server:
  port: 30000
